### ISSUE TITLE
Error running game

### ISSUE THREAD

**Issue by mamal72** [mdibaiee/node-games#1]
Hi. I'm getting this error running the game:

``` bash
/Users/mamal/.nvm/versions/node/v4.2.2/lib/node_modules/node-games/spacecraft.js:1
(function (exports, require, module, __filename, __dirname) { import Unit from './classes/unit';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mamal/.nvm/versions/node/v4.2.2/lib/node_modules/node-games/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/mamal/.nvm/versions/node/v4.2.2/lib/node_modules/node-games/index.js:16:1)
    at Module._compile (module.js:435:26)
```

**Comment by mdibaiee** [comment]
@mamal72: Thanks, it's fixed now.
